### ISSUE TITLE
Svelte VS Code extension's linter is not working with script="ts"

### ISSUE THREAD

**Issue by schachdavid** [pyoner/svelte-typescript#11]
**Describe the bug**
Linting does not work with the svelte vs code extension if the script tag has lang="ts". 
Preprocessors seems to work with this fine so the extension is probably the problem. Simple fix is just to replace lang="ts" with lang="typescript" in the script tag.

**To Reproduce**
1. Use the template in vs code with the extension.

**Expected behavior**
Linting should work.

**Comment by itzikHagoel** [comment]
I had the same issue but replacing the tag had no effect.
I have found the solution here: https://github.com/UnwrittenFun/svelte-vscode/issues/39
Would be nice if the file is included out of the box.

>  In order to get rid of the parse-errors, you want to create a svelte.config.js file like this:

```
const { preprocess } = require("@pyoner/svelte-ts-preprocess")

module.exports = {
  preprocess: preprocess()
}
```

> Reload VSCode and the errors should be gone.
