### ISSUE TITLE
Two missing dev dependencies

### ISSUE THREAD

**Issue by itzikHagoel** [pyoner/svelte-typescript#14]
**Describe the bug**
I followed the instructions in README.md.
It seems to assume the user has typescript installed globally (which I don't on this machine),
so it fails to run:

> $ npm run dev
> ...
> (node:22185) UnhandledPromiseRejectionWarning: Error: Cannot find module 'typescript'
> ...

after adding typescript as a dev dependency (yarn add -D typescript) it runs fine but still complains about missing type definitions:

> $ npm run dev
> ...
> rpt2: options error TS2688: Cannot find type definition file for '@pyoner/svelte-types'.
> rpt2: options error TS2688: Cannot find type definition file for '@pyoner/svelte-types'.
> error TS2688: Cannot find type definition file for '@pyoner/svelte-types'.
> 
> error TS2688: Cannot find type definition file for '@pyoner/svelte-types'.
> 
> error TS2688: Cannot find type definition file for '@pyoner/svelte-types'.
> 
> error TS2688: Cannot find type definition file for '@pyoner/svelte-types'.
> 
> ✔ server (4.9s)
> ✔ client (4.4s)
> ✔ service worker (18ms)
> > Listening on http://localhost:3000
> 
> 

Adding your type definitions (yarn add -D @pyoner/svelte-types) makes the errors go away :)

I suggest you add these dev dependencies to package.json.
It is not critical in any way but might discourage newcomers.

**To Reproduce**
described above

**Expected behavior**
everything works out of the box with no issues and the user is blown away by how slick the demo app is :)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version: 77 

**Additional context**
Thanks much for creating this! it is super helpful and saves time

**Comment by pyoner** [comment]
Ok, I will check.
Thanks!

**Comment by pyoner** [comment]
@itzikHagoel sorry for the delay
I have fixed!

**Comment by itzikHagoel** [comment]
Thanks! I appreciate it
