### ISSUE TITLE
(rpt2 plugin) Error: main.ts(9,13): semantic error TS2351: Cannot use 'new' with an expression whose type lacks a call or constr uct signature.

### ISSUE THREAD

**Issue by joshua1** [pyoner/svelte-typescript#2]
Hi @pyoner i am trying to use your typescript template and getting the error 
```(rpt2 plugin) Error: /web/src/main.ts(9,13): semantic error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.```
which sort of makes sense given that the App.Svelte has no default export 

How do you get around this

**Comment by pyoner** [comment]
Hi @joshua1 
Can't reproduce the bug
Can you show me `package-lock.json` file?
