### ISSUE TITLE
Typescript error: Cannot find name "variable" (Labelled statement)

### ISSUE THREAD

**Issue by ChaitanyaGadodia** [pyoner/svelte-typescript#22]
**Describe the bug**
Labelled statement reactive declaration, typescript gives out this error:
<img width="857" alt="Screenshot 2020-02-12 at 9 26 40 AM" src="https://user-images.githubusercontent.com/10559670/74301672-c9c90f00-4d79-11ea-9399-827694b7e818.png">

source code: https://github.com/ChaitanyaGadodia/svelte-init/blob/master/src/components/Nav.svelte

**Comment by pyoner** [comment]
You should define a variable type before assigning:
```typescript
export let segment: string | undefined;
let extra: string | undefined;
$: extra = segment;
```

or add `let`:
```typescript
export let segment: string | undefined;
$: let extra = segment;
```

**Comment by ChaitanyaGadodia** [comment]
So using let inside the labelled statement gives this error
`
export let segment: string | undefined;
$: let extra = segment;
`

> The keyword 'let' is reserved (3:4)

But defining the variable before hand works just fine and also the complied JS is same in both the cases.
Thanks @pyoner
