### ISSUE TITLE
Importing interface from .ts file to svelte component doesn't work

### ISSUE THREAD

**Issue by Oreilles** [pyoner/svelte-typescript#23]
foo.ts :
```typescript
export interface Foo {}
```

index.svelte :
```svelte
<script lang=typescript>
    import { Foo } from '.../foo'
</script>
```

result:
```
Non-existent export 'Foo' is imported from '.../foo.ts'
```

Is there a way to make this work ?

**Comment by pyoner** [comment]
Hi @Oreilles !
You have a misspelled word "typescript" in your code:
```html
<script lang=typscript>
    import { Foo } from '.../foo'
</script>
```

**Comment by Oreilles** [comment]
Thanks, corrected, but unrelated to the issue unfortunately...

**Comment by pyoner** [comment]
Could you create a git repo with your source code?

**Comment by Oreilles** [comment]
Here's a fork of your project, you can replicate the issue in the `sapper-template`
 folder. https://github.com/Oreilles/svelte-typescript

**Comment by pyoner** [comment]
ok, I'll check
thanks!

**Comment by pyoner** [comment]
The problem is that the preprocessor only transplie typescript to js code.
Transpilation cannot check the imported data whether they are types (interface, type, etc.) or js objects.

**Comment by pyoner** [comment]
But we must preserve all imports excluding types!
Because some importing data is used only in html
```svelte
<script>
	import { blur } from 'svelte/transition';
</script>

{#if condition}
	<div transition:blur="{{amount: 10}}">
		fades in and out
	</div>
{/if}
```

**Comment by Oreilles** [comment]
Typescript interfaces will disappear at compilation anyway - I just don't get why we could import an interface from a `.ts` file to another one, but not to a `.svelte` document's typescript `<script>` tag.

**Comment by pyoner** [comment]
In our case the interfaces will not disappear, because we must preserve all imports, look at this code https://github.com/pyoner/svelte-typescript/blob/master/packages/preprocess/src/svelte-ts-preprocess.ts#L11 

By default `typescript` remove all imported interfaces or types at compile time, but we must preserve them, because we don't know the imported data is types or just `js` objects (look at the `AST` of the imported data https://ts-ast-viewer.com/#code/JYWwDg9gTgLgBAbzgMQhOBfOAzKERwDkAdKQPTZqFA)

The `AST` gives us that `Foo` is just `SyntaxKind.Identifier`

**Comment by Nostin** [comment]
I'm having this problem too.  TypeScript support isn't much use if we can't import things like interfaces.  Is there a way around this issue yet?

**Comment by Oreilles** [comment]
The workaround is to write the code for your component in an external `.ts` file, then import that file in your component with the svelte-preprocess feature: 
```
<script src="file.ts" lang="ts" />
```

**Comment by pyoner** [comment]
> I'm having this problem too. TypeScript support isn't much use if we can't import things like interfaces. Is there a way around this issue yet?

We can ignore this warning (`NON_EXISTENT_EXPORT`) by simply replacing the `onwarn` function in rollup.config.js to:
```js
const onwarn = (warning, onwarn) => {
  if (warning.code === "NON_EXISTENT_EXPORT") return;

  (warning.code === "CIRCULAR_DEPENDENCY" &&
    /[/\\]@sapper[/\\]/.test(warning.message)) ||
    onwarn(warning);
};
```

This is a simple solution

**Comment by pyoner** [comment]
Another solution is not trivial.
To detect importing types need to analyze the `AST` code and find these types and remove them from the import

**Comment by Nostin** [comment]
Maybe I'm missing something but the error still exists for me with the above suggestions and looks like it's treated as an Error not a warning

![image](https://user-images.githubusercontent.com/4354558/80304767-810ee700-87fb-11ea-8a56-754e6eae565e.png)

**Comment by pyoner** [comment]
> Maybe I'm missing something but the error still exists for me with the above suggestions and looks like it's treated as an Error not a warning
> 
> ![image](https://user-images.githubusercontent.com/4354558/80304767-810ee700-87fb-11ea-8a56-754e6eae565e.png)

Your error is not related to this issue.
Please, check your code https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module

**Comment by david02871** [comment]
@Nostin @pyoner I get the same error (instead of a warning) if I have the Svelte compiler option `dev` set as true. https://svelte.dev/docs#svelte_compile

I created a minimal example here https://github.com/david02871/svelte-typescript-interface-error

Am I using the incorrect export style? I had a look at https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module

**Comment by pyoner** [comment]
Hi @david02871
Thank you for the report!

> Am I using an incorrect export style?

No.

Currently I'm working on this issue, it takes time to implement some features

**Comment by pyoner** [comment]
> Maybe I'm missing something but the error still exists for me with the above suggestions and looks like it's treated as an Error not a warning
> 
> ![image](https://user-images.githubusercontent.com/4354558/80304767-810ee700-87fb-11ea-8a56-754e6eae565e.png)

Sorry! The bug is related to the preprocessor

**Comment by pyoner** [comment]
@Nostin @david02871 I found that the error appears when using `rollup-commonjs-plugin` above version 9.3.4

Try to install `npm i -D rollup-commonjs-plugin@9.3.4`

**Comment by pyoner** [comment]
I have updated the commonjs plugin https://github.com/pyoner/svelte-typescript/commit/f25cd3bd7a313b8ac9745f28e0706113a8a6804e

@Nostin @david02871 
Can you check the update?

**Comment by pyoner** [comment]
I have updated preprocessor (ver 1.3.0) 
Now you can use: 
```typescript
import type { Foo } from  './foo'
```
But you need to use `typescript` version >= 3.8 see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Comment by jsdw** [comment]
Thanks for the fix here @pyoner!

I'm used to being able to import types and variables in a single import (I've used Parcel + React previously and am fairly new to Svelte), eg

```
import { someVariable, SomeType } from './foo'
``` 

VSCode and svelte-check seem happy with thi s, but Rollup kicks up a fuss with the whole `[!] Error: 'SomeType' is not exported by...` error. Are there any plans to support that, or do we need to split type and variable imports in Rollup+Svelte land and have the below?

```
import { someVariable } from './foo'
import type { SomeType } from './foo'
```

My preference would be that the single import of variable+type works of course, but mainly I just want to have my expectations set here.

**Comment by pyoner** [comment]
Hi @jsdw 
Yes, you should split imports!

Take a look at the official documentation https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#typescript---limitations

> As we're only transpiling, it's not possible to import types or interfaces into your svelte component without using the new TS 3.8 type import modifier: import type { SomeInterface } from './MyModule' otherwise bundlers will complain that the name is not exported by MyModule.

I recommend you to use https://github.com/sveltejs/svelte-preprocess because it is the official preprocessor.
I have no plans to continue to support this preprocessor.
