### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by pjebs** [pyoner/svelte-typescript#24]
I'm relatively inexperienced at FE Engineering. Is there a tutorial on how to even get this up and running.

**Comment by pyoner** [comment]
Hi @pjebs!
Follow this instruction https://github.com/pyoner/svelte-typescript/tree/master/packages/template#readme

**Comment by stilet** [comment]
npm i - Error
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: template@1.0.0
npm ERR! Found: rollup@2.56.3
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^2.19.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-terser@4.0.4
npm ERR! node_modules/rollup-plugin-terser
npm ERR!   dev rollup-plugin-terser@"^4.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/leo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leo/.npm/_logs/2021-08-23T08_14_41_756Z-debug.log
`
`

**Comment by pyoner** [comment]
Sorry the project is closed! Use instead the official template.
