### ISSUE TITLE
I declaration file ignored

### ISSUE THREAD

**Issue by retog** [pyoner/svelte-typescript#26]
**Describe the bug**
Locally added declaration (.d.ts) files are ignored

**To Reproduce**
1. import a module (@example/module) for which there is no declaration file
2. Build the project
3. Get the error
```
 Could not find a declaration file for module '@example/module'. '[...]' implicitly has an 'any' type.
  Try `npm install @types/example__module` if it exists or add a new declaration (.d.ts) file containing `declare module '@example/module';`
```
4. add a file called `typed.d.ts` containing `declare module '@example/module';` to the source folder
5. build again
6. see the same error message

**Expected behavior**
The error should no appear again

**Additional context**
The problem only occurs when the import is in the `.svelte` file, when the import is in a separate `.ts` file, the error no longer appears after adding the declaration file.

**Comment by pyoner** [comment]
Hi @retog !
If you don't have a declaration file then you can set a property `allowJs` to `true` in the `tsconfig.json` file 
https://github.com/pyoner/svelte-typescript/blob/master/packages/template/tsconfig.json#L9

**Comment by retog** [comment]
Hi @pyoner !

Thanks for the suggestion. Unfortunately setting `allowJs` had no inpact. However setting `strict` to false got rid of the message.
