### ISSUE TITLE
vscode does not report type errors using template

### ISSUE THREAD

**Issue by hbbio** [pyoner/svelte-typescript#27]
**Describe the bug**
Introducing a simple type error is not shown with vscode (maybe this is a vscode problem).

**To Reproduce**
1. Clone the template as per README (in particular, `svelte.config.js` is set).
2. Start `npm run dev`
3. Introduce a type error, i.e. `let step: number = "yes";` in `Counter.svelte`.
4. In terminal, we see properly: `error TS2322: Type '"yes"' is not assignable to type 'number'.` but vscode is still happy!

**Expected behavior**
vscode should show the type error.

**Screenshots**
<img width="969" alt="Screenshot 2020-05-24 at 11 18 05" src="https://user-images.githubusercontent.com/808274/82750412-44112280-9db0-11ea-987e-0ce532b8c9f5.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - vscode 1.45.1, svelte plugin 0.9.3, svelte intellisense 0.7.1

**Comment by pyoner** [comment]
Hi @hbbio!

Yes, this is a problem with the vscode svelte plugin.
You can send a report to https://github.com/sveltejs/language-tools

**Comment by hbbio** [comment]
Thanks, I'm not sure I know enough what's required on their side in the specific use case of Svelte development in TS... 
I'll try to investigate a bit before submitting an issue there. Don't hesitate to share anything I can specifically look at!
