### ISSUE TITLE
Use definition file without overriding others

### ISSUE THREAD

**Issue by leontepe** [pyoner/svelte-typescript#29]
Adding `"types": ["@pyoner/svelte-types"]` to my `tsconfig.json` makes my TypeScript compiler miss all other npm packages I imported.

Is there a different way to use these definition files without having this effect?

Also, shouldn't type declarations be published under `@types/...`? I think that would make TypeScript find the types for Svelte by default...?

**Comment by pyoner** [comment]
Hi @leontepe 
Don't use '@pyoner/svelte-types' is deprecated
Use the official svelte types 
See an example https://github.com/pyoner/svelte-typescript/blob/master/packages/template/tsconfig.json#L47
