### ISSUE TITLE
[FEAT] Add ability to turn off diagnostics/errors

### ISSUE THREAD

**Issue by Teoxoy** [pyoner/svelte-typescript#3]
**Describe the solution you'd like**
I would like to turn on/off an option that would toggle the diagnostics/errors in the console.
i.e. disable this:

https://github.com/pyoner/svelte-typescript/blob/ab679023478ee4065bf627a0d49d63bb8956275c/packages/preprocess/src/svelte-ts-preprocess.ts#L192-L200

**Additional context**
I currently use the svelte plugin for VSCode that supports ts inside script elements so I don't need diagnostics/errors in the console.

I mainly want an option to do this because the preprocessor shows false positives in the console. This is because I use rollup plugins for other TS files and the file gets transformed before it gets passed to the typescript rollup plugin.

To get this functionality asap in my project I just copied `svelte-ts-preprocess` from dist and commented out the mentioned lines.
I can put up a PR for this if you want.

**Comment by pyoner** [comment]
Hi @Teoxoy 
Could you make a PR?

**Comment by Teoxoy** [comment]
Sure thing.
