### ISSUE TITLE
typescript should be moved to peerDependencies

### ISSUE THREAD

**Issue by IlyaSemenov** [pyoner/svelte-typescript#8]
Typescript is currently listed as a direct module dependency, which is logically incorrect. This is up to a developer to manage Typescript version (and that's what people actually do). 

With the current way of things, the developers may accidentally end up with **two** versions of Typescripts living in their project (one installed by themselves, another one silently pulled by svelte-typescript).

I believe typescript should be moved to peerDependencies.

**Comment by pyoner** [comment]
Sorry for the delay!
I think you're right
I will fix it

**Comment by pyoner** [comment]
@IlyaSemenov fixed!
