### ISSUE TITLE
Instructions for VSCODE

### ISSUE THREAD

**Issue by cortopy** [pyoner/svelte-typescript#9]
**Is your feature request related to a problem? Please describe.**

The template does not work out of the box with vscode

**Describe the solution you'd like**

The issue is resolved in https://github.com/UnwrittenFun/svelte-vscode/issues/39

Just add the svelte.config.js as:

```
const { preprocess } = require("@pyoner/svelte-ts-preprocess")

module.exports = {
  preprocess: preprocess()
}
```

**Describe alternatives you've considered**
I would do a PR but I'm not sure if this only affects Vscode. If that's the case, then maybe a paragraph in the README would do. Otherwise, this file should be in the template

**Comment by pyoner** [comment]
@cortopy 
Could you do a PR?
You can add instructions to https://github.com/pyoner/svelte-typescript/blob/master/packages/template/README.md

Thank you!

**Comment by cortopy** [comment]
Please see https://github.com/pyoner/svelte-typescript/pull/10
